### ISSUE TITLE
Create a workshop model for Government Financial Report hackathon

### ISSUE THREAD

**Issue by sarob** [opendatainitiative/opendatalegislation#17]
document workshops in the repo for states and cities to copy. Does Sunlight Foundation have something we can copy/use?

**Comment by sarob** [comment]
A bit of history where Marc and Sunlight got together in 2014 https://sunlightfoundation.com/2014/01/30/pdf-liberation-hackathon-and-the-need-for-more-civic-innovation/

**Comment by sarob** [comment]
open data day planned for Walnut Creek
https://www.eventbrite.com/e/contra-costa-civic-hackathon-tickets-43005029200

Is this as complicated this kind of hack session needs to be or should we create/utilize a project to hack on?

schedule
Schedule:
8:30 AM Registration and breakfast
9:15 AM Opening presentation and lightning talks by government officials and tech experts
9:45 AM Project pitches
10:30 AM Start Hacking
12:30 PM Lunch
1:30 PM More Hacking
4:00 PM Project demos/Prizes

**Comment by joffemd** [comment]
This schedule was adopted from Code for San Francisco.  It is not a single-project event.  Anyone can pitch anything related to open data.

**Comment by sarob** [comment]
More issues on this here https://github.com/ContraCostaCivic/FiscalData/issues
