### ISSUE TITLE
XBRL can be part of legislation standard

### ISSUE THREAD

**Issue by sarob** [opendatainitiative/opendatalegislation#6]
XBRL can be part of legislation standard for DataOhio board standards implementation. It should be neutral to include OKI frictionless financial data package standard.

**Comment by sarob** [comment]
Sunlight Foundation has been writing to the Municipal Securities Rulemaking Board (MSRB). Where is the intersection of GASB responsibilities and MSRB?

https://sunlightfoundation.com/2014/04/28/asking-for-top-level-changes-to-help-boost-local-financial-transparency/
https://sunlightfoundation.com/2014/02/05/a-case-of-incomplete-reforms-leaving-improved-disclosures-locked-up/

**Comment by joffemd** [comment]
Much of this was at my instigation.  MSRB could implement XBRL reporting of CAFRs but has not done so.  GASB has a project page for what it calls “Electronic Financial Reporting” but hasn’t kept it updated.

**Comment by sarob** [comment]
We can use marc's post as content to add to the project https://www.linkedin.com/pulse/florida-legislature-votes-migrate-local-government-cafrs-marc-joffe/

**Comment by sarob** [comment]
Posted by Christian to the [12 March 2018 ODI Advisory Council meeting](https://docs.google.com/document/d/13No6EIjtrVDbQbOBEA-YpR-9ZgsQFZ5CR27NSROb6Hg/edit?usp=sharing).
HR 5054, XBRL filing for corporations, SEC requires filing in XBRL, this bill would limit XBRL filing to public companies $250M plus - https://www.congress.gov/bill/115th-congress/house-bill/5054
Backstory blog - https://www.datacoalition.org/house-financial-services-committee-approves-anti-open-data-proposal-again/
Data Foundation paper on XBRL filings at the SEC - https://www.datafoundation.org/xbrl-report-2017/

**Comment by sarob** [comment]
Additional bits on the Florida Municipal CAFR XBRL Bill. It is landmark as it is the first state legislation to codify a reporting standard. HR1073 passed house, senate. Build XBRL taxonomy, for XBRL CAFRs, implementation 2022.
 It basically slipped through the legislature with little debate because the Florida Chief Financial Officer’s office supported it. This effort was kicked off by the CEO of a startup in the Data Coalition, Rachel Carpenter of Intrinio. I drafted the original version of the language and handled back-and-forth with the sponsor.
http://www.flsenate.gov/Session/Bill/2018/01073

**Comment by sarob** [comment]
HR1073 passed house, senate, signed in late march
$500K appropriation, money available 2019,  july 2018 out to vendors for requests
Marc working with USF on prototype for St. Petersburg, intent to make it available before July 2019 to help Florida with vendor selection

**Comment by joffemd** [comment]
Money available on July 1, 2018 (which is the start of 2019 fiscal year).  Goal is to finish prototype by July 1, 2018.

**Comment by joffemd** [comment]
For more see:  https://reason.org/commentary/florida-passes-first-in-the-nation-data-reporting-standards-to-improve-local-government-financial-transparency/

**Comment by sarob** [comment]
Ah right thanks for the correction.


~ sean
