### ISSUE TITLE
Making Ohio GA132-HR3 lines 86-88 more clear

### ISSUE THREAD

**Issue by sarob** [opendatainitiative/opendatalegislation#7]
With respect to Ohio HB3, Section 117.432(B) states the following:

"Within two years after the effective date of this section, the auditor of state shall establish, by rule adopted under Chapter 119. of the Revised Code, appropriate uniform accounting procedures and charts of accounts that may be used by all public offices. Public offices that maintain their financial
records in accordance with the rules established by the auditor of state under this section shall be declared by the auditor of state to have earned a "DataOhio Transparency Award—Uniformity of Accounting."

This provision could be readily modified to bring in machine readable standards and thus mandate XBRL or Frictionless Data formatted CAFRs.  To conform with what Christian is doing on the federal level, I suggest the following revision (additions in bold):

"Within two years after the effective date of this section, the auditor of state shall establish, by rule adopted under Chapter 119. of the Revised Code, appropriate uniform accounting procedures and charts of accounts that may be used by all public offices. **The chart of accounts shall be consistent with standards promulgated by the Governmental Accounting Standards Board.  The auditor will also establish an electronic reporting standard for public offices that will render their accounting information fully searchable and machine readable, that will be non-proprietary and that will incorporate standards developed and maintained by voluntary consensus standards bodies.** Public offices that maintain their financial records in accordance with the rules established by the auditor of state under this section shall be declared by the auditor of state to have earned a "DataOhio Transparency Award—Uniformity of Accounting."

Do you or others on this chain have thoughts about the proposed additions?  If this is agreeable to everyone, how might this change be proposed to Representative Duffey?

**Comment by joffemd** [comment]
It is important the the legislation specifically mention "Governmental Accounting Standards" promulgated by GASB.  New Jersey and a couple of other states deviate from GASB standards rendering local disclosures not nationally comparable.  Would be a shame if Ohio went down that road.

**Comment by sarob** [comment]
I will add HR40 as it covers this. It is almost like an amendment.

**Comment by sarob** [comment]
I updated the scoring of the ohio legislation as 57 out 100, as the existing legislation is missing some of the attributes that should be in there. Scoring based on https://github.com/opendatainitiative/opendatainitiative.github.io/blob/master/scoring.md. I am working on improving https://github.com/opendatainitiative/opendatalegislation/tree/master/how-to as the model legislation that would result in a score of 100. Your thoughts on both documents are welcome.
